global.params.p1=8098
global.params.p2=9009
spring.h2.console.enabled=true
spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=http://Localhost:8761/eureka
eureka.instance.prefer-ip-address=true
management.endpoints.web.exposure.include =* 